export const PROJECTS = [
    {
        id: 5,
        title: "Interesting Places",
        category: "Side Project",
        span: "md:col-span-2",
        description: "Discovering and sharing interesting places around the world.",
        color: "from-emerald-600",
        accent: "#059669",
        pastel: "#C9F0DC",
        pastelHover: "#A3E4C4",
        href: "/playground/interestingplaces",
        image: "/assets/img4.jpg",
        mockup: "/assets/interestingplaces-video.mov",
        mockupRadius: "rounded-t-[0.5rem]",
        mockupBg: false,
    },
    {
        id: 1,
        title: "Guest User EKG Recording",
        category: "Mobile Design",
        span: "md:col-span-1",
        description: "Designing a new way to record EKG readings for patients.",
        color: "from-amber-600",
        accent: "#d97706",
        pastel: "#FFE8A3",
        pastelHover: "#FFD666",
        href: "/work/guest-user",
        image: "/assets/img1.jpg",
        mockup: "/assets/projects/guest-ekg/after.png",
        mockupBg: false,
        mockupFit: "phone",
    },
    {
        id: 7,
        title: "Design System",
        category: "Design System",
        span: "md:col-span-1",
        description: "Foundations and components for a healthcare product that had outgrown itself.",
        color: "from-teal-600",
        accent: "#0f9b8b",
        pastel: "#C7E4FF",
        pastelHover: "#8FC4FF",
        href: "/work/kardia-design-system",
        image: "/assets/kardia-ds/kardia-ds-card.png",
        mockup: "/assets/kardia-ds/Mockup-DS-crop.png",
        mockupBg: false,
        mockupFit: "phone",
    },
    {
        id: 6,
        title: "Freshfolios",
        category: "Side Project",
        span: "md:col-span-2",
        description: "A platform for designers to showcase their work.",
        color: "from-rose-600",
        accent: "#e11d48",
        pastel: "#FFD6E0",
        pastelHover: "#FFB3C7",
        href: "/playground/freshfolios",
        image: "/assets/img4.jpg",
        mockup: "/assets/Freshfolios.png",
        mockupRadius: "rounded-t-[0.5rem]",
        mockupBg: false,
    },
];
