export const PROJECTS = [
    {
        id: 1,
        title: "Guest User EKG Recording",
        category: "Mobile Design",
        span: "md:col-span-2",
        description: "Designing a new way to record EKG readings for patients.",
        color: "from-amber-600",
        text: "text-white",
        href: "/work/guest-user",
        image: "/assets/img1.jpg",
    },
    {
        id: 2,
        title: "Year In Review",
        category: "Growth Design",
        span: "md:col-span-1",
        description: "Year in review design for our Premium subscribers.",
        color: "from-indigo-600",
        text: "text-black",
        href: "/work/year-in-review",
        image: "/assets/img2.jpg",
    },
    {
        id: 3,
        title: "Kardia Design System",
        category: "Design System",
        span: "md:col-span-1",
        description: "Consumer mobile app design system.",
        color: "from-blue-600",
        text: "text-black",
        href: "/work/kardia-design-system",
        image: "/assets/img3.jpg",
    },
    {
        id: 4,
        title: "Website Redesign",
        category: "Web Design",
        span: "md:col-span-2",
        description:
            "Redesign and Webflow development of the website for a software company.",
        color: "from-lime-600",
        text: "text-white",
        href: "/work/website-redesign",
        image: "/assets/img4.jpg",
    },
    {
        id: 5,
        title: "Interesting Places",
        category: "Side Project",
        span: "md:col-span-1",
        description: "Discovering and sharing interesting places around the world.",
        color: "from-emerald-600",
        text: "text-white",
        href: "/playground/interestingplaces",
        image: "/assets/img4.jpg",
    },
    {
        id: 6,
        title: "Freshfolios",
        category: "Side Project",
        span: "md:col-span-2",
        description: "A platform for designers to showcase their work.",
        color: "from-rose-600",
        text: "text-white",
        href: "/playground/freshfolios",
        image: "/assets/img4.jpg",
    },
];
