export const PROJECTS = [
    {
        id: 1,
        title: "Guest User EKG Recording",
        category: "Mobile Design",
        span: "md:col-span-2",
        description: "Designing a new way to record EKG readings for patients.",
        color: "from-amber-600",
        accent: "#d97706",
        pastel: "#FFE8A3",
        pastelHover: "#FFD666",
        href: "/work/guest-user",
        image: "/assets/img1.jpg",
        mockup: "/assets/projects/guest-ekg/guest-1.png",
    },
    {
        id: 2,
        title: "Year In Review",
        category: "Growth Design",
        span: "md:col-span-1",
        description: "Year in review design for our Premium subscribers.",
        color: "from-indigo-600",
        accent: "#4f46e5",
        pastel: "#CBD5FF",
        pastelHover: "#ADBCFF",
        href: "/work/year-in-review",
        image: "/assets/img2.jpg",
        mockup: "",
    },
    {
        id: 3,
        title: "Kardia Design System",
        category: ["Design System", "Mobile Design"],
        span: "md:col-span-1",
        description: "Consumer mobile app design system.",
        color: "from-blue-600",
        accent: "#2563eb",
        pastel: "#C7E4FF",
        pastelHover: "#9FD0FF",
        href: "/work/kardia-design-system",
        image: "/assets/img3.jpg",
        mockup: "/assets/projects/guest-ekg/after.png",
    },
    {
        id: 4,
        title: "Website Redesign",
        category: "Web Design",
        span: "md:col-span-2",
        description:
            "Redesign and Webflow development of the website for a software company.",
        color: "from-lime-600",
        accent: "#65a30d",
        pastel: "#D3EEC8",
        pastelHover: "#B5E39F",
        href: "/work/website-redesign",
        image: "/assets/img4.jpg",
        mockup: "",
    },
    {
        id: 5,
        title: "Interesting Places",
        category: "Side Project",
        span: "md:col-span-1",
        description: "Discovering and sharing interesting places around the world.",
        color: "from-emerald-600",
        accent: "#059669",
        pastel: "#C9F0DC",
        pastelHover: "#A3E4C4",
        href: "/playground/interestingplaces",
        image: "/assets/img4.jpg",
        mockup: "/assets/interestingplaces-video.mov",
    },
    {
        id: 6,
        title: "Freshfolios",
        category: "Side Project",
        span: "md:col-span-2",
        description: "A platform for designers to showcase their work.",
        color: "from-rose-600",
        accent: "#e11d48",
        pastel: "#FFD6E0",
        pastelHover: "#FFB3C7",
        href: "/playground/freshfolios",
        image: "/assets/img4.jpg",
        mockup: "/assets/Freshfolios.png",
    },
];
